### ISSUE TITLE
"__dataPayload" is not defined (PylancereportUndefinedVariable)

### ISSUE THREAD

**Issue by Hemant40** [PaloAltoNetworks/PrismaSASECloudManaged-Python#9]
## Describe the bug

Hi, While running this code i found a issue which shows that the __dataPayload is undefined.

## Expected behavior

code needs to be updated with the required variables. If __dataPayload is required please update in the code.

## Current behavior

Getting error for "__dataPayload" is not defined (PylancereportUndefinedVariable) in sasiApi.py file.

## Steps to reproduce

from auth import saseAuthentication
from access import prismaAccess
from access import policyObjects

p = saseAuthentication.saseAuthentication()
p.prismaAccessAuth("your TSD_ID","Client_id","Client_secert")
n = prismaAccess.prismaAccess(p.saseToken)
o = policyObjects.policyObjects(n)

o.paTagsListTags()

## Screenshots

![image](https://user-images.githubusercontent.com/91174172/220033612-f6317376-0d56-4618-aec0-98014da0c661.png)

## Error-details:

(.venv) PS C:\C4I\Hemant_20_02_prismamananged\PrismaSASECloudManaged-Python> python.exe .\test.py
Traceback (most recent call last):
  File "C:\C4I\Hemant_20_02_prismamananged\PrismaSASECloudManaged-Python\test.py", line 10, in <module>
    o.paTagsListTags()
  File "C:\C4I\Hemant_20_02_prismamananged\PrismaSASECloudManaged-Python\access\policyObjects.py", line 47, in paTagsListTags
    paTag.paList(__folder)
  File "C:\C4I\Hemant_20_02_prismamananged\PrismaSASECloudManaged-Python\access\saseApi.py", line 12, in paList     
    __response = requests.get(url=self.saseUri, headers=self.saseAuthHeaders, data=__dataPayload)
**NameError: name '_saseApi__dataPayload' is not defined**

## Your Environment

(.venv) PS C:\C4I\Hemant_20_02_prismamananged\PrismaSASECloudManaged-Python> python.exe --version
Python 3.10.10

**Comment by Hemant40** [comment]
++ Correct image showing that the variable is not defined.
![image](https://user-images.githubusercontent.com/91174172/220034141-077bf91f-464e-400f-87be-53b876402331.png)

**Comment by nopg** [comment]
I just ran into this myself. It looks like a typo/incorrect recent edit in my opinion. The old version had "params=__params" instead of "data=__dataPayload". I changed this back on my own fork and it works for my only use case so far.
